crater-invoice/crater

- database/seeds/CurrenciesTableSeeder.php
- resources/assets/js/views/settings/UpdateApp.vue
> fix(CurrenciesTableSeeder): added missing currency KWD

- Dockerfile
> Docker: fix update functionality

- app/Http/Controllers/OnboardingController.php
I've added pt_BR and AR langs to language list in onboarding, because they can be selected from Settings page after installation but not during the install process.
> Added available languages to Onboarding

- app/Http/Controllers/EstimatesController.php
- app/Http/Controllers/InvoicesController.php
- app/Http/Controllers/PaymentController.php
- app/Mail/EstimatePdf.php
- app/Mail/EstimateViewed.php
- app/Mail/InvoicePdf.php
- app/Mail/InvoiceViewed.php
- app/Mail/PaymentPdf.php
- app/Mail/invoicePdf.php
- resources/views/emails/viewed/estimate.blade.php
- resources/views/emails/viewed/invoice.blade.php
This PR changes three things:
1. Subject lines of emails to customers now include the company name.
2. Respect the global From Name and Email address as set in **Settings > Mail Configuration** when sending emails to customers.
3. Contents of Viewed emails now includes the customer's name.
> More descriptive email fields.

- package.json
cross-env should only be in devDependencies
Reported in Discord: https://discordapp.com/channels/646980514410135573/646980514410135576/667506932021723156
> cross-env should only be in devDependencies

- database/seeds/CurrenciesTableSeeder.php
As requested by @vbezruchkin in issue #113
> Added Kyrgyzstani som

- resources/assets/js/bootstrap.js
- resources/assets/js/store/modules/auth/actions.js
- resources/assets/js/views/auth/Login.vue
This improved error handling will take care of network errors and laravel errors, even if they are in an array.
A good way to test this could be in the login screen trying to login with an incorrect password until you see a notification saying you are rate limited until x seconds
Let me know if I have to change anything
> Improved error handling

- composer.json
To help other existed project to require
> Change project name in composer.json

- docker-compose.yml
This is compatible even if you decide you don't want to go with the changes in #220 ;-)
> [Docker] Dive the direction to persist database on the host rather than a volume if desired

- .gitignore
.gitignore's magic still eludes me it seems!
> Added last slash so it ignores everything in the folder

- resources/views/app/pdf/estimate/estimate3.blade.php
- resources/views/app/pdf/invoice/invoice2.blade.php
- resources/views/app/pdf/invoice/invoice3.blade.php
- resources/views/app/pdf/payment/payment.blade.php
- resources/views/app/pdf/reports/expenses.blade.php
- resources/views/app/pdf/reports/profit-loss.blade.php
- resources/views/app/pdf/reports/sales-customers.blade.php
- resources/views/app/pdf/reports/sales-items.blade.php
- resources/views/app/pdf/reports/tax-summary.blade.php
DomPDF font-weight problems fix
> PDF templates fix

- config/crater.php
@mohitpanjwani you merged before my push of the commit.
> update code for SR

- resources/assets/js/components/base/modal/ItemUnitModal.vue
- resources/assets/js/components/base/modal/NoteModal.vue
- resources/assets/js/components/base/modal/PaymentModeModal.vue
> Showing length error for Payment, Note and ItemUnit Model Views

- resources/assets/js/views/invoices/Create.vue
Bug: 
Wrong breadcrumb when editing invoices
> Fixed small typo that caused wrong breadcrumb

- resources/views/app/pdf/invoice/invoice1.blade.php
- resources/views/app/pdf/invoice/invoice3.blade.php
> Don't capitalize address on invoice

- .github/workflows/ci.yaml
- composer.lock
Add automated CLI test via github workflow, that run on every PR and on every commit
> Add test ci

- app/Models/Estimate.php
- app/Models/Invoice.php
- app/Models/Payment.php
Attachments are now translated in the language set under preferences.
> fix(attachments): Fixed language on pdf attachments

- resources/assets/js/components/base/BaseNotification.vue
- resources/assets/js/views/auth/ForgotPassword.vue
Hey,
This tiny PR will fix : 
- 1 typo in `resources/assets/js/components/base/BaseNotification.vue`
- 1 typo in `resources/assets/js/views/auth/ForgotPassword.vue`
Cheers! :robot:
> docs: fix typos

- app/Http/Controllers/V1/Dashboard/DashboardController.php
What do you think about showing only non-draft invoices on the dashboard?
I figure that until an invoice is sent, it doesn't need to be shown on any overviews or reports. (In my case, I have prepared a few future invoices that won't be sent for some time, and it would be nice for the dashboard to reflect only actual sent/paid invoices)
-----
An invoice cannot be considered due if it has not been sent (and thus
still a 'DRAFT').
This change adds a `WHERE status != 'DRAFT'` to each invoice query in
the dashboard controller.
Additionally, this change replaces `->get()->count()` calls to just
`->count()`, which should be equivalent and more efficient.
> Only show non-draft invoices on dashboard

- readme.md
Checked new functionalities from the 5.0 update. And separated some combined functionalities
> Checked new functionalities from the 5.0 update.

- database/migrations/2021_07_01_060700_create_user_company_table.php
Fixing a typo in name of schema.
> Typo error

- resources/scripts/components/dropdowns/InvoiceIndexDropdown.vue
This fixes issue #404 by allowing a user to resend an invoice on the invoice view page.
> Allow invoices to be sent/resent from the invoice view page

- app/Http/Controllers/V1/Admin/Expense/ExpensesController.php
- app/Http/Controllers/V1/Admin/Expense/UploadReceiptController.php
- app/Http/Controllers/V1/Admin/Settings/CompanyController.php
- app/Http/Requests/AvatarRequest.php
- app/Http/Requests/CompanyLogoRequest.php
- app/Http/Requests/ExpenseRequest.php
- app/Rules/Base64Mime.php
@mohitpanjwani https://huntr.dev/bounties/d7453360-baca-4e56-985f-481275fa38db/
> Unrestricted file upload fix

- database/seeders/CurrenciesTableSeeder.php
Added **Macedonian Denar** currency, https://www1.oanda.com/currency/iso-currency-codes/MKD.
> Added Macedonian Denar currency

- app/Http/Requests/Customer/CustomerProfileRequest.php
- tests/Unit/Request/Customer/CustomerProfileTest.php
@mohitpanjwani https://huntr.dev/bounties/19f3e5f7-b419-44b1-9c37-7e4404cbec94/
> Customer avatar validation

- app/Http/Resources/Customer/InvoiceResource.php
- app/Http/Resources/EstimateResource.php
- app/Http/Resources/PaymentResource.php
Fixes #754
Fixes the resolve issues in the views (Invoice, Payments and Estimate) for the customer.
> Customer view field resolve fix

- readme.md
> Update readme.md to Fix API Documentation URL

- app/Http/Controllers/V1/Admin/Settings/UpdateCompanySettingsController.php
- tests/Feature/Admin/CompanySettingTest.php
After company has transactions you get error on all update settings requests, which is now solved.
> Fix currency settings error

- app/Http/Requests/UploadExpenseReceiptRequest.php
@mohitpanjwani https://huntr.dev/bounties/4d7d4fc9-e0cf-42d3-b89c-6ea57a769045/
> Expense attachment validation fix

- app/Http/Controllers/V1/Admin/Modules/UnzipModuleController.php
- app/Http/Controllers/V1/Admin/Modules/UploadModuleController.php
- app/Http/Requests/UnzipUpdateRequest.php
- app/Http/Requests/UploadModuleRequest.php
@mohitpanjwani https://huntr.dev/bounties/cb9a0393-be34-4021-a06c-00c7791c7622/
> Module upload validation

- resources/views/app/pdf/invoice/invoice1.blade.php
There is no class "header" that's why I removed it. Also I fixed some whitespace issues
> Improve invoice 1 template css

- app/Models/Invoice.php
It would be nice if any variables in the email subject would also be replaced.
> Send invoice email: replace variables in email subject

- docker-compose/cron.dockerfile
Resolves php7-bcmath package not found issue as described in #937
> Bump PHP version to 8 from 7.4

- app/Console/Commands/CreateTemplateCommand.php
Creation message now includes the views disk in its path.
> Fix incorrect invoice template creation message in artisan
