config/app.php
In `config/app.php` there was a space at the start of the file.
This caused `headers_sent()` to return true and also breaks any attempts to set a `Content-Type` header later in execution, which in turn causes the issue seen in https://github.com/bytefury/crater/issues/14
I have no idea why this is an issue in some versions of Apache (or your web server of choice) and not others, works fine in Ubuntu 19.04 for me but breaks in CentOS 7.7.
Simply removing the space fixes the issue.
=> Removed a space that forced apache to send the wrong headers

resources/assets/js/views/settings/Preferences.vue, resources/assets/js/views/wizard/Settings.vue
This PR improves the select input that allows users to choose a currency by appending the currency code to the label. This allows users to search a currency by code instead of name.
Both the preferences page and the on-boarding wizard inputs are concerned.
=> Prepend currency code to label to allow searching by currency code

resources/assets/js/views/customers/Create.vue
In my previous PR https://github.com/bytefury/crater/pull/43, it forgot to add the functionality to the customer create/edit form. This new PR addresses that. Hopefully I did not miss another one.
=> Add missing currency code to customer create/edit form

database/migrations/2019_09_14_120124_create_media_table.php
The JSON SQL datatype is not supported in some of the SQL servers (i.e. 5.6.44). Replaced it with TEXT datatype.
=> Removed JSON SQL datatype, Replaced with TEXT Type

app/Address.php
There was a bug with the addresses when the application was used with PostgreSQL, because this is case-sensitive and while the constants were written in upper case, they were saved in lower case.
I fixed it by changing the value of the constants to lowercase, which are used only once.
=> Fix case sensitive PostgreSQL bug

Dockerfile
Fix for "Empty PDF rendered in Docker" https://github.com/bytefury/crater/issues/69
Generation does not work due to:
```
iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed
```
Installing the library `gnu-libiconv` will solve the problem
=> Fix for "Empty PDF rendered in Docker #69"

composer.json
As requested in the Discord #general channel, here's the PR for auto-adding the .env file and generating a app key if it doesn't exist.
=> Detect if no .env file exists and add it on composer commands.

resources/assets/js/views/expenses/Create.vue
Previoulsy a string with contents "null" is transmitted and saved to the database when updating an expense with an empty note. This fix prevents that.
Please note that this fix still needs to be compiled with npm.
=> Fixed small bug that might occur when an expense is updated

.gitignore, docker-compose.yml, docker-compose/nginx/nginx.conf, docker-compose/php/uploads.ini
When I successfully did the install with Docker, the first time I saw was that uploading a document in an expense would result in an `HTTP 413` error. Time to change the upload file size !
This PR sets an extra config for php, in `docker-compose/php/uploads.ini` that's bind-mounted to the `app` container.  Then, I added a value to the `docker-compose/nginx/nginx.conf` to reflect the values of the uploads.ini file.
This enables files up to 64M, but anyone could change it to their taste.
=> [Docker] Modify php and nginx config to change upload file size

resources/views/app/pdf/payment/payment.blade.php
Fixed the currency not being displayed in receipts. The problem there was that the format_money_pdf() will return 
`<span style="font-family: DejaVu Sans;">$</span>xxxxx` 
which means that the float:right was applied to both spans, making the currency symbol to not be visible.
This fixes the issue [357](https://github.com/bytefury/crater/issues/357)
=> fix(payments): display the currency in receipts

resources/views/app/pdf/invoice/invoice1.blade.php, resources/views/app/pdf/invoice/invoice2.blade.php, resources/views/app/pdf/invoice/invoice3.blade.php
seems box-sizing Property is not supported by DOMPDF. just deleted the css rules so DOMPDF will render the PDFs even if you turn on `config/domdpdf.php 'show_warnings' => true`
=> Fixes #371

app/Models/EstimateItem.php, app/Models/InvoiceItem.php, database/migrations/2021_03_03_155223_add_unit_name_to_pdf.php, resources/views/app/pdf/estimate/partials/table.blade.php, resources/views/app/pdf/invoice/partials/table.blade.php
- Added the unit name in invoices and estimates pdf templates after the quantity where items have a unit set
- This is NOT backwards compatible, meaning the old invoices and estimates will not display the unit_name. in order to have this on older invoices you need to edit the invoices/estimates, remove the item from the invoice and re-add the item(s) and save the invoice.
=> fix(items): added unit name after quantity in the pdf templates

database/seeders/CurrenciesTableSeeder.php, resources/assets/js/helpers/utilities.js
Adjust money format to respect `swap_currency_symbol`:
Also places the € symbol after the amount. While there are some countries writing the € before the amount (4 out of 28), most countries don't do that:
https://en.wikipedia.org/wiki/Language_and_the_euro#Written_conventions_for_the_euro_in_the_languages_of_EU_member_states
Hence I switched the position. In the future, there should be an option in the app setting, that allows the user to easily set this on his own (without the need to edit the database entry).
Closes #415
=> Adjust money format to respect swap_currency_symbol

resources/assets/js/views/estimates/ItemSelect.vue
There is a limit on the description of the estimate vue which is not necessary.
The field in the database is in TEXT.
=> Delete limit 255 description estimate

resources/assets/js/plugins/ar.json, resources/assets/js/plugins/de.json, resources/assets/js/plugins/en.json, resources/assets/js/plugins/es.json, resources/assets/js/plugins/fa.json, resources/assets/js/plugins/fi.json, resources/assets/js/plugins/fr.json, resources/assets/js/plugins/hi.json, resources/assets/js/plugins/it.json, resources/assets/js/plugins/ja.json, resources/assets/js/plugins/ko.json, resources/assets/js/plugins/lv.json, resources/assets/js/plugins/nl.json, resources/assets/js/plugins/pl.json, resources/assets/js/plugins/pt.json, resources/assets/js/plugins/ro.json, resources/assets/js/plugins/ru.json, resources/assets/js/plugins/sk.json, resources/assets/js/plugins/sr.json, resources/assets/js/plugins/sv.json, resources/assets/js/plugins/tr.json, resources/assets/js/plugins/vi.json, resources/assets/js/plugins/zh.json, resources/views/app/pdf/invoice/partials/table.blade.php
When an invoice has tax per item enabled, include a tax column so that
it's clear how much tax is being applied to each item.
=> Add tax column to invoices

resources/scripts/components/estimate-invoice-common/CreateItemRow.vue
Fixes #630 
Sets the minimum item quantity to >=0, rather than >=1.
=> fix: make min item quantity 0 instead of 1

app/Traits/GeneratesPdfTrait.php
Escape html special characters from the $fields array to prevent html injection in the generated pdfs.
Before:
After:
Note:
This does **not** break the formatting avaliable for fields in the customisation section, allowing customisation to still be possible.
=> Fix HTML injection vulnerability 

resources/sass/crater.scss
Crater attempts to load the Poppins semi-bold font file with `Poppins-Semibold.ttf` but the file is actually `SemiBold`, so this causes a 404 error.
=> fix: Poppins semi-bold font 404 error

app/Traits/GeneratesPdfTrait.php
Fixes #773 
To reproduce the issue, company setting **save_pdf_to_disk** should be set  to **YES**.
=> PDF download naming

resources/scripts/admin/views/estimates/Index.vue, resources/scripts/admin/views/invoices/Index.vue, resources/scripts/admin/views/recurring-invoices/Index.vue
The proposal here is to arrange the Estimates, Invoices and Recurring Invoices index page to display the tab group filters in a more natural flow. As a user, you would expect that when you select either of these items you're presented with a list of all of them, then you can willing filter down by their status i.e. Due, Sent, Draft.
I'll also work on creating a PR to the Crater mobile repo so that the user experience stays consitent across the use of Crater applications.﻿
=> Arrange Invoice, Recurring Invoices and Estimate Tab groups for a more natural flow

database/seeders/CurrenciesTableSeeder.php
As a central African resident (precisely in Cameroon), the default support of the XAF currency is needed.
=> add default support for Central African currency

docker-compose/setup.sh
Running ./docker-compose/setup.sh throws an error with allow-plugins:
```
In PluginManager.php line 744:
pestphp/pest-plugin contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe.                           
You can run "composer config --no-plugins allow-plugins.pestphp/pest-plugin [true|false]" to enable it (true) or disable it explicitly and suppress this exception (false)  
See https://getcomposer.org/allow-plugins 
```
Added `docker compose exec app composer config --no-plugins allow-plugins.pestphp/pest-plugin true` to setup script.
Resolves the following duplicate issues:
fixes #1006
fixes  #1015
=> Patch setup.sh script to deploy without plugins error.

Dockerfile
Version 7.4 no longer works when running docker-compose/setup.sh. Updated to 8.1 in Dockerfile. Issue is now resolved and Crater sets up as expected without version conflicts.
=> Update php version to 8.1 in Dockerfile

.github/workflows/uffizzi-build.yml, uffizzi/Dockerfile, uffizzi/nginx/Dockerfile
This PR solves the problem with front-end files compiling —  in the preview deployment.
During the building process it cleans up `/var/www/public/build` folder, and after that it builds the front end on the same path.
The preview is deployed [here](https://app.uffizzi.com//github.com/daramayis/f-crater/pull/4).
Issue: https://github.com/crater-invoice/crater/issues/1097
=> feat: front-end files bulding

.gitignore, config/installer.php
ZIP is listed as a requirement for install but it's not checked for when installing or upgrading.
=> Adds Zip to the required PHP Extension check
